[project]
name = "ogas"
version = "0.1.0"
description = "OGAS"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.15.2",
    "faststream[kafka]>=0.5.39",
    "pydantic-settings>=2.9.1",
    "python-ulid[pydantic]>=3.0.0",
    "sqlalchemy>=2.0.40",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]

[tool.uv]
python-downloads = "manual"
python-preference = "only-system"
