[project]
name = "ogas"
version = "0.1.0"
description = "OGAS"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "alembic>=1.15.2",
    "alembic-postgresql-enum>=1.7.0",
    "alembic-utils>=0.8.8",
    "asyncpg>=0.30.0",
    "faststream[kafka]>=0.5.40",
    "prefect>=3.4.1",
    "prefect-docker>=0.6.4",
    "pydantic-settings>=2.9.1",
    "python-ulid[pydantic]>=3.0.0",
    "sqlalchemy[asyncio]>=2.0.40",
]

[dependency-groups]
dev = [
    "polyfactory>=2.21.0",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
]

[tool.uv]
python-downloads = "manual"
python-preference = "only-system"

[tool.pytest.ini_options]
asyncio_mode = "auto"
#asyncio_default_fixture_loop_scope = "session"

