"""Upgrade  Stock model1

Revision ID: 0736fea65fb2
Revises: dd3a2c1a4254
Create Date: 2025-06-19 15:35:37.836168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types


# revision identifiers, used by Alembic.
revision: str = '0736fea65fb2'
down_revision: Union[str, None] = 'dd3a2c1a4254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE organizationstock drop constraint if exists ck_organizationstock_in_stock_positive')
    op.execute('ALTER TABLE organizationstock add constraint ck_organizationstock_in_stock_positive check ( in_stock >= 0 )')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
