"""Uniqie idx for product

Revision ID: 08f1c3b6ca7d
Revises: 21c0296ab50f
Create Date: 2025-05-09 13:59:56.685714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types


# revision identifiers, used by Alembic.
revision: str = '08f1c3b6ca7d'
down_revision: Union[str, None] = '21c0296ab50f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_product_name'), 'product', ['name', 'unit', 'standard_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_product_name'), 'product', type_='unique')
    # ### end Alembic commands ###
