"""Comments

Revision ID: 17c42ed74e6e
Revises: b8f71c3a9315
Create Date: 2025-05-07 16:20:43.897703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17c42ed74e6e'
down_revision: Union[str, None] = 'b8f71c3a9315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'name',
               existing_type=sa.TEXT(),
               comment='Наименование продукта.',
               existing_nullable=False)
    op.alter_column('product', 'unit',
               existing_type=postgresql.ENUM('BOX', 'PACKET', 'PLASTIC_BOTTLE', 'GLASS_BOTTLE', 'PALLET', 'IN_BULK', 'CONTAINER', 'CISTERN', 'WITHOUT_PACKAGE', name='productunit'),
               comment='Категория продукта',
               existing_nullable=False)
    op.alter_column('product', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Время создания.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Время обновления.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Время обновления.',
               existing_nullable=True)
    op.alter_column('product', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Время создания.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product', 'unit',
               existing_type=postgresql.ENUM('BOX', 'PACKET', 'PLASTIC_BOTTLE', 'GLASS_BOTTLE', 'PALLET', 'IN_BULK', 'CONTAINER', 'CISTERN', 'WITHOUT_PACKAGE', name='productunit'),
               comment=None,
               existing_comment='Категория продукта',
               existing_nullable=False)
    op.alter_column('product', 'name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Наименование продукта.',
               existing_nullable=False)
    # ### end Alembic commands ###
