"""ON DELETE

Revision ID: 21c0296ab50f
Revises: c2f668d77c01
Create Date: 2025-05-09 13:48:57.542247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21c0296ab50f'
down_revision: Union[str, None] = 'c2f668d77c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_category_association_table_category_code_category'), 'category_association_table', 'category', ['category_code'], ['code'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_category_association_table_product_id_product'), 'category_association_table', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product', 'unit',
               existing_type=postgresql.ENUM('BOX', 'PACKET', 'PLASTIC_BOTTLE', 'GLASS_BOTTLE', 'PALLET', 'IN_BULK', 'CONTAINER', 'CISTERN', 'WITHOUT_PACKAGE', name='productunit'),
               comment='Фасовка продукта.',
               existing_comment='Категория продукта',
               existing_nullable=False)
    op.drop_constraint('fk_product_standard_code_standard', 'product', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_standard_code_standard'), 'product', 'standard', ['standard_code'], ['code'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_product_standard_code_standard'), 'product', type_='foreignkey')
    op.create_foreign_key('fk_product_standard_code_standard', 'product', 'standard', ['standard_code'], ['code'])
    op.alter_column('product', 'unit',
               existing_type=postgresql.ENUM('BOX', 'PACKET', 'PLASTIC_BOTTLE', 'GLASS_BOTTLE', 'PALLET', 'IN_BULK', 'CONTAINER', 'CISTERN', 'WITHOUT_PACKAGE', name='productunit'),
               comment='Категория продукта',
               existing_comment='Фасовка продукта.',
               existing_nullable=False)
    op.drop_constraint(op.f('fk_category_association_table_product_id_product'), 'category_association_table', type_='foreignkey')
    op.drop_constraint(op.f('fk_category_association_table_category_code_category'), 'category_association_table', type_='foreignkey')
    # ### end Alembic commands ###
