"""Add hash into Organization

Revision ID: 26153be784d0
Revises: 43716b86bda1
Create Date: 2025-05-29 15:31:32.376479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types


# revision identifiers, used by Alembic.
revision: str = '26153be784d0'
down_revision: Union[str, None] = '43716b86bda1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('token', sa.VARCHAR(length=60), nullable=True, comment='Токен организации в виде хеша.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'token')
    # ### end Alembic commands ###
