"""Add product table

Revision ID: 3b71ca806938
Revises: 
Create Date: 2025-05-05 16:13:08.303908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b71ca806938'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('BOX', 'PACKET', 'PLASTIC_BOTTLE', 'GLASS_BOTTLE', 'PALLET', 'IN_BULK', 'CONTAINER', 'CISTERN', 'WITHOUT_PACKAGE', name='productunit').create(op.get_bind())
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('unit', postgresql.ENUM('BOX', 'PACKET', 'PLASTIC_BOTTLE', 'GLASS_BOTTLE', 'PALLET', 'IN_BULK', 'CONTAINER', 'CISTERN', 'WITHOUT_PACKAGE', name='productunit', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    sa.Enum('BOX', 'PACKET', 'PLASTIC_BOTTLE', 'GLASS_BOTTLE', 'PALLET', 'IN_BULK', 'CONTAINER', 'CISTERN', 'WITHOUT_PACKAGE', name='productunit').drop(op.get_bind())
    # ### end Alembic commands ###
