"""Create OperativeDataORM

Revision ID: 40eca069e8f7
Revises: 9dcd0336d4d2
Create Date: 2025-06-11 12:50:22.089625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40eca069e8f7'
down_revision: Union[str, None] = '9dcd0336d4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operativedata',
    sa.Column('product_id', common.orm_models.custom_types.ULID(), nullable=False, comment='Продукт.'),
    sa.Column('organization_id', common.orm_models.custom_types.ULID(), nullable=False, comment='Компания.'),
    sa.Column('diff', sa.Float(), nullable=False, comment='Приход или расход продукта в единицах измерения.'),
    sa.Column('change_datetime', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='Время наступления события.')
    )
    op.execute(
        """
        SELECT create_hypertable('operativedata', by_range('change_datetime', INTERVAL '1 day'));
        """
    )
    op.execute(
        """
         alter table public.operativedata SET(
           timescaledb.enable_columnstore,
           timescaledb.orderby = 'change_datetime DESC',
           timescaledb.segmentby = 'product_id, organization_id'
           );
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operativedata')
    # ### end Alembic commands ###
