"""Add Role into Capability

Revision ID: 4329c53fa210
Revises: 26153be784d0
Create Date: 2025-06-09 12:50:57.604380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4329c53fa210'
down_revision: Union[str, None] = '26153be784d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PRODUCER', 'CONSUMER', name='role').create(op.get_bind())
    op.add_column('capability', sa.Column('role', postgresql.ENUM('PRODUCER', 'CONSUMER', name='role', create_type=False), nullable=False, comment='В качестве производителя или потребителя товара.'))
    op.drop_constraint(op.f('uq_capability_product_id'), 'capability', type_='unique')
    op.create_unique_constraint(op.f('uq_capability_product_id'), 'capability', ['product_id', 'organization_id', 'period', 'role'])
    op.alter_column('category_association_table', 'product_id',
               existing_type=common.orm_models.custom_types.ULID(),
               comment='Продукт',
               existing_nullable=False)
    op.alter_column('category_association_table', 'category_code',
               existing_type=sa.VARCHAR(length=12),
               comment='Код категории',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_association_table', 'category_code',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Код категории',
               existing_nullable=False)
    op.alter_column('category_association_table', 'product_id',
               existing_type=common.orm_models.custom_types.ULID(),
               comment=None,
               existing_comment='Продукт',
               existing_nullable=False)
    op.drop_constraint(op.f('uq_capability_product_id'), 'capability', type_='unique')
    op.create_unique_constraint(op.f('uq_capability_product_id'), 'capability', ['product_id', 'organization_id', 'period'], postgresql_nulls_not_distinct=False)
    op.drop_column('capability', 'role')
    sa.Enum('PRODUCER', 'CONSUMER', name='role').drop(op.get_bind())
    # ### end Alembic commands ###
