"""Add minute view

Revision ID: 4cf33b7e94ff
Revises: 40eca069e8f7
Create Date: 2025-06-17 13:30:34.431239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from center.orm_models import OperativeDataORM1MinuteView

# revision identifiers, used by Alembic.
revision: str = '4cf33b7e94ff'
down_revision: Union[str, None] = '40eca069e8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    OperativeDataORM1MinuteView.create(op)
    op.execute(
       f'ALTER MATERIALIZED VIEW {OperativeDataORM1MinuteView.__table__.name} '
       f'set (timescaledb.enable_columnstore = true);'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    OperativeDataORM1MinuteView.drop(op)
