"""Add minute view

Revision ID: 4cf33b7e94ff
Revises: 40eca069e8f7
Create Date: 2025-06-17 13:30:34.431239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from center.orm_models import OperativeDataORM1MinuteView

# revision identifiers, used by Alembic.
revision: str = '4cf33b7e94ff'
down_revision: Union[str, None] = '40eca069e8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    OperativeDataORM1MinuteView.create(op)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('operativedata_change_datetime_idx'), 'operativedata', [sa.literal_column('change_datetime DESC')], unique=False)
    # ### end Alembic commands ###
    OperativeDataORM1MinuteView.drop(op)
