"""Add NecessityORM model

Revision ID: 50ed770814c6
Revises: 0736fea65fb2
Create Date: 2025-06-26 15:28:53.412838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50ed770814c6'
down_revision: Union[str, None] = '0736fea65fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('necessity',
    sa.Column('id', common.orm_models.custom_types.ULID(), server_default=sa.text('gen_monotonic_ulid()'), nullable=False, comment='Primary key :: ULID.'),
    sa.Column('product_id', common.orm_models.custom_types.ULID(), nullable=False, comment='Продукт.'),
    sa.Column('to_produce', sa.Float(), nullable=False, comment='Необходимое кол-во продукта для заказа.'),
    sa.Column('in_stock_at_consumer', sa.Float(), nullable=False, comment='Кол-во на складах потребителей.'),
    sa.Column('in_stock_at_producer', sa.Float(), nullable=False, comment='Кол-во на складах производителей.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания.'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_necessity_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_necessity'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('necessity')
    # ### end Alembic commands ###
