"""Add hour view

Revision ID: 57556cd8fd40
Revises: 70f6f87931a1
Create Date: 2025-06-18 13:51:37.221039

"""
from typing import Sequence, Union

from alembic import op

from center.orm_models import OperativeDataORM1HourView

# revision identifiers, used by Alembic.
revision: str = '57556cd8fd40'
down_revision: Union[str, None] = '70f6f87931a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    OperativeDataORM1HourView.create(op)
    op.execute(
       f'ALTER MATERIALIZED VIEW {OperativeDataORM1HourView.__table__.name} '
       f'set (timescaledb.enable_columnstore = true);'
    )
    OperativeDataORM1HourView.add_continuous_aggregate_policy(op)
    OperativeDataORM1HourView.add_columnstore_policy(op)
    OperativeDataORM1HourView.add_retention_policy(op)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    OperativeDataORM1HourView.drop(op)

