"""Partitionning

Revision ID: 599f3f2c6c69
Revises: 57556cd8fd40
Create Date: 2025-06-18 15:29:37.625174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '599f3f2c6c69'
down_revision: Union[str, None] = '57556cd8fd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capability')
    op.drop_index(op.f('operativedata_change_datetime_idx'), table_name='operativedata')
    sa.Enum('HOUR', 'DAY', 'WEEK', 'MONTH', 'QUARTER', 'YEAR', name='period').drop(op.get_bind())
    sa.Enum('PRODUCER', 'CONSUMER', name='role').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PRODUCER', 'CONSUMER', name='role').create(op.get_bind())
    sa.Enum('HOUR', 'DAY', 'WEEK', 'MONTH', 'QUARTER', 'YEAR', name='period').create(op.get_bind())
    op.create_index(op.f('operativedata_change_datetime_idx'), 'operativedata', [sa.literal_column('change_datetime DESC')], unique=False)
    op.create_table('capability',
    sa.Column('id', common.orm_models.custom_types.ULID(), server_default=sa.text('gen_monotonic_ulid()'), autoincrement=False, nullable=False, comment='Primary key :: ULID.'),
    sa.Column('organization_id', common.orm_models.custom_types.ULID(), autoincrement=False, nullable=False, comment='Компания.'),
    sa.Column('product_id', common.orm_models.custom_types.ULID(), autoincrement=False, nullable=False, comment='Продукт.'),
    sa.Column('period', postgresql.ENUM('HOUR', 'DAY', 'WEEK', 'MONTH', 'QUARTER', 'YEAR', name='period', create_type=False), autoincrement=False, nullable=False, comment='Период за который указана производительность.'),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True, comment='Производительность, единиц товара.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Время создания.'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Время обновления.'),
    sa.Column('role', postgresql.ENUM('PRODUCER', 'CONSUMER', name='role', create_type=False), autoincrement=False, nullable=False, comment='В качестве производителя или потребителя товара.'),
    sa.CheckConstraint('value >= 0', name=op.f('ck_capability_value_gt_0_check')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_capability_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_capability_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability')),
    sa.UniqueConstraint('product_id', 'organization_id', 'period', 'role', name=op.f('uq_capability_product_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
