"""Add product table

Revision ID: 6428a3d06b1a
Revises: 
Create Date: 2025-05-05 15:42:41.681679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6428a3d06b1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('unit', postgresql.ENUM('BOX', 'PACKET', 'PLASTIC_BOTTLE', 'GLASS_BOTTLE', 'PALLET', 'IN_BULK', 'CONTAINER', 'CISTERN', 'WITHOUT_PACKAGE', name='productunit'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
