"""change unique idx

Revision ID: 683d2cff1768
Revises: 8bf4b7e81bef
Create Date: 2025-05-23 12:34:12.723008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types


# revision identifiers, used by Alembic.
revision: str = '683d2cff1768'
down_revision: Union[str, None] = '8bf4b7e81bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_capability_organization_id', 'capability', type_='unique')
    op.create_unique_constraint(op.f('uq_capability_product_id'), 'capability', ['product_id', 'organization_id', 'period'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_capability_product_id'), 'capability', type_='unique')
    op.create_unique_constraint('uq_capability_organization_id', 'capability', ['organization_id', 'product_id', 'period'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
