"""Add field standard_code into Production

Revision ID: 81b8fd0eff52
Revises: a4eeb106031c
Create Date: 2025-05-08 15:15:39.872443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types


# revision identifiers, used by Alembic.
revision: str = '81b8fd0eff52'
down_revision: Union[str, None] = 'a4eeb106031c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('standard_code', sa.TEXT(), nullable=False, comment='Код стандарта, например ГОСТ ХХ-ХХХ'))
    op.alter_column('product', 'id',
               existing_type=common.orm_models.custom_types.ULID(),
               comment='Primary key :: ULID.',
               existing_nullable=False,
               existing_server_default=sa.text('gen_monotonic_ulid()'))
    op.create_foreign_key(op.f('fk_product_standard_code_standard'), 'product', 'standard', ['standard_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_product_standard_code_standard'), 'product', type_='foreignkey')
    op.alter_column('product', 'id',
               existing_type=common.orm_models.custom_types.ULID(),
               comment=None,
               existing_comment='Primary key :: ULID.',
               existing_nullable=False,
               existing_server_default=sa.text('gen_monotonic_ulid()'))
    op.drop_column('product', 'standard_code')
    # ### end Alembic commands ###
