"""fix enum

Revision ID: 8bf4b7e81bef
Revises: e1277becc3d0
Create Date: 2025-05-21 10:24:14.194691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '8bf4b7e81bef'
down_revision: Union[str, None] = 'e1277becc3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='period',
        new_values=['HOUR', 'DAY', 'WEEK', 'MONTH', 'QUARTER', 'YEAR'],
        affected_columns=[TableReference(table_schema='public', table_name='capability', column_name='period')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='period',
        new_values=['HOUR', 'DAY', 'WEEK', 'MONTH', 'YEAR'],
        affected_columns=[TableReference(table_schema='public', table_name='capability', column_name='period')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
