"""Partitionning1

Revision ID: 9ec443634d2a
Revises: 599f3f2c6c69
Create Date: 2025-06-18 16:00:43.315467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ec443634d2a'
down_revision: Union[str, None] = '599f3f2c6c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PRODUCER', 'CONSUMER', name='role').create(op.get_bind())
    sa.Enum('HOUR', 'DAY', 'WEEK', 'MONTH', 'QUARTER', 'YEAR', name='period').create(op.get_bind())
    op.create_table('capability',
    sa.Column('id', common.orm_models.custom_types.ULID(), server_default=sa.text('gen_monotonic_ulid()'), nullable=False, comment='id'),
    sa.Column('organization_id', common.orm_models.custom_types.ULID(), nullable=False, comment='Компания.'),
    sa.Column('product_id', common.orm_models.custom_types.ULID(), nullable=False, comment='Продукт.'),
    sa.Column('period', postgresql.ENUM('HOUR', 'DAY', 'WEEK', 'MONTH', 'QUARTER', 'YEAR', name='period', create_type=False), nullable=False, comment='Период за который указана производительность.'),
    sa.Column('role', postgresql.ENUM('PRODUCER', 'CONSUMER', name='role', create_type=False), nullable=False, comment='В качестве производителя или потребителя товара.'),
    sa.Column('value', sa.Integer(), nullable=True, comment='Производительность, единиц товара.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания.'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='Время обновления.'),
    sa.CheckConstraint('value >= 0', name=op.f('ck_capability_value_gt_0_check')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_capability_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_capability_product_id_product'), ondelete='CASCADE'),
    sa.UniqueConstraint('product_id', 'organization_id', 'period', 'role', name=op.f('uq_capability_product_id')),
    postgresql_partition_by='LIST (role)'
    )

    op.execute("create table capability_prod partition of capability for values in ('PRODUCER'::role);")
    op.execute("create table capability_cons partition of capability for values in ('CONSUMER'::role);")
    op.create_primary_key('pk_capability_prod', 'capability_prod', ['id'])
    op.create_primary_key('pk_capability_cons', 'capability_cons', ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capability')
    sa.Enum('HOUR', 'DAY', 'WEEK', 'MONTH', 'QUARTER', 'YEAR', name='period').drop(op.get_bind())
    sa.Enum('PRODUCER', 'CONSUMER', name='role').drop(op.get_bind())
    # ### end Alembic commands ###
