"""Create Standard table

Revision ID: a4eeb106031c
Revises: 17c42ed74e6e
Create Date: 2025-05-07 16:47:00.122126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4eeb106031c'
down_revision: Union[str, None] = '17c42ed74e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard',
    sa.Column('oks_code', postgresql.ARRAY(sa.TEXT()), nullable=False, comment='Код ОКС.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания.'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='Время обновления.'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Признак активности.'),
    sa.Column('code', sa.TEXT(), nullable=False, comment='Код стандарта, например ГОСТ ХХ-ХХХ'),
    sa.Column('description', sa.TEXT(), nullable=False, comment='Краткое описание стандарта.'),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standard')
    # ### end Alembic commands ###
