"""Create Plan model

Revision ID: a805eeb939e2
Revises: 8542cd8e0380
Create Date: 2025-07-02 16:48:11.934091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a805eeb939e2'
down_revision: Union[str, None] = '8542cd8e0380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', common.orm_models.custom_types.ULID(), server_default=sa.text('gen_monotonic_ulid()'), nullable=False, comment='Primary key :: ULID.'),
    sa.Column('organization_id', common.orm_models.custom_types.ULID(), nullable=True, comment='Компания. None - план на закупку заграницей.'),
    sa.Column('product_id', common.orm_models.custom_types.ULID(), nullable=False, comment='Продукт.'),
    sa.Column('value', sa.Float(), nullable=False, comment='Необходимо произвести единиц продукта.'),
    sa.Column('fact_time', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='Время вычисления необходимости в пр-ве продукта.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), sa.Computed('ulid_to_timestamp(id)', ), nullable=False, comment='Время создания записи.'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_plan_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_plan_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan'))
    )
    op.create_index('ix_created_at_desc', 'plan', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_plan_organization_id'), 'plan', ['organization_id'], unique=False)
    op.create_index(op.f('ix_plan_product_id'), 'plan', ['product_id'], unique=False)
    # op.drop_index(op.f('necessity_created_at_idx'), table_name='necessity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('necessity_created_at_idx'), 'necessity', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_plan_product_id'), table_name='plan')
    op.drop_index(op.f('ix_plan_organization_id'), table_name='plan')
    op.drop_index('ix_created_at_desc', table_name='plan')
    op.drop_table('plan')
    # ### end Alembic commands ###
