"""Create m2m table for Category

Revision ID: c2f668d77c01
Revises: e4c9437d4fc5
Create Date: 2025-05-09 12:56:13.414120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types


# revision identifiers, used by Alembic.
revision: str = 'c2f668d77c01'
down_revision: Union[str, None] = 'e4c9437d4fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_association_table',
    sa.Column('product_id', common.orm_models.custom_types.ULID(), nullable=False),
    sa.Column('category_code', sa.VARCHAR(length=12), nullable=False),
    sa.PrimaryKeyConstraint('product_id', 'category_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_association_table')
    # ### end Alembic commands ###
