"""Create OperativeDataORM

Revision ID: cb775e4d2fe7
Revises: 9dcd0336d4d2
Create Date: 2025-06-11 12:32:23.569521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb775e4d2fe7'
down_revision: Union[str, None] = '9dcd0336d4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operativedata',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, cycle=True), nullable=False, comment='ID'),
    sa.Column('organization_id', common.orm_models.custom_types.ULID(), nullable=False, comment='Компания.'),
    sa.Column('product_id', common.orm_models.custom_types.ULID(), nullable=False, comment='Продукт.'),
    sa.Column('diff', sa.Float(), nullable=False, comment='Приход или расход продукта в единицах измерения.'),
    sa.Column('change_datetime', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='Время наступления события.'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operativedata'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operativedata')
    # ### end Alembic commands ###
