"""Create Organization model

Revision ID: d7b7a0725e13
Revises: 27c12e6b1122
Create Date: 2025-05-19 13:21:14.577770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7b7a0725e13'
down_revision: Union[str, None] = '27c12e6b1122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', common.orm_models.custom_types.ULID(), server_default=sa.text('gen_monotonic_ulid()'), nullable=False, comment='Primary key :: ULID.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания.'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='Время обновления.'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Признак активности.'),
    sa.Column('name', sa.TEXT(), nullable=False, comment='Название организации.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    # ### end Alembic commands ###
