"""Create Stock model

Revision ID: dd3a2c1a4254
Revises: 9ec443634d2a
Create Date: 2025-06-19 14:17:05.558563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd3a2c1a4254'
down_revision: Union[str, None] = '9ec443634d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizationstock',
    sa.Column('organization_id', common.orm_models.custom_types.ULID(), nullable=False, comment='Компания.'),
    sa.Column('product_id', common.orm_models.custom_types.ULID(), nullable=False, comment='Продукт.'),
    sa.Column('in_stock', sa.Float(), nullable=False, comment='Остаток продукта на складе.'),
    sa.Column('min_level', sa.Float(), server_default=sa.text("'0'"), nullable=False, comment='Уровень, ниже которого остаток опускаться не должен.'),
    sa.Column('max_level', sa.Float(), server_default=sa.text("'Infinity'"), nullable=False, comment='Максимальная вместимость склада по данному продукту.'),
    sa.Column('necessity', sa.Float(), nullable=True, comment='Нужна в продукте переданная от организации'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания.'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='Время обновления.'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Признак активности.'),
    sa.CheckConstraint('in_stock > 0', name=op.f('ck_organizationstock_in_stock_positive')),
    sa.CheckConstraint('max_level > 0', name=op.f('ck_organizationstock_max_level_positive')),
    sa.CheckConstraint('min_level < max_level', name=op.f('ck_organizationstock_min_max_level')),
    sa.CheckConstraint('min_level >= 0', name=op.f('ck_organizationstock_min_level_positive')),
    sa.CheckConstraint('necessity > 0', name=op.f('ck_organizationstock_necessity_level_positive')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_organizationstock_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_organizationstock_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'product_id', name=op.f('pk_organizationstock'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizationstock')
    # ### end Alembic commands ###
