"""Create Capability model

Revision ID: e1277becc3d0
Revises: d7b7a0725e13
Create Date: 2025-05-19 15:51:19.931978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1277becc3d0'
down_revision: Union[str, None] = 'd7b7a0725e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('HOUR', 'DAY', 'WEEK', 'MONTH', 'YEAR', name='period').create(op.get_bind())
    op.create_table('capability',
    sa.Column('id', common.orm_models.custom_types.ULID(), server_default=sa.text('gen_monotonic_ulid()'), nullable=False, comment='Primary key :: ULID.'),
    sa.Column('organization_id', common.orm_models.custom_types.ULID(), nullable=False, comment='Компания.'),
    sa.Column('product_id', common.orm_models.custom_types.ULID(), nullable=False, comment='Продукт.'),
    sa.Column('period', postgresql.ENUM('HOUR', 'DAY', 'WEEK', 'MONTH', 'YEAR', name='period', create_type=False), nullable=False, comment='Период за который указана производительность.'),
    sa.Column('value', sa.Integer(), nullable=True, comment='Производительность, единиц товара.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания.'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='Время обновления.'),
    sa.CheckConstraint('value >= 0', name=op.f('ck_capability_value_gt_0_check')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_capability_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_capability_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability')),
    sa.UniqueConstraint('organization_id', 'product_id', 'period', name=op.f('uq_capability_organization_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capability')
    sa.Enum('HOUR', 'DAY', 'WEEK', 'MONTH', 'YEAR', name='period').drop(op.get_bind())
    # ### end Alembic commands ###
