"""Create table Category

Revision ID: e4c9437d4fc5
Revises: 81b8fd0eff52
Create Date: 2025-05-08 17:56:32.548779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import common.orm_models.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4c9437d4fc5'
down_revision: Union[str, None] = '81b8fd0eff52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания.'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='Время обновления.'),
    sa.Column('code', sa.VARCHAR(length=12), nullable=False, comment='Код категории продукта.'),
    sa.Column('name', sa.TEXT(), nullable=False, comment='Наименование категории продукта.'),
    sa.Column('main_prefix', sa.VARCHAR(length=2), sa.Computed('code::varchar(2)', ), nullable=False, comment='Главный префикс кода (главная категория).'),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
